version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - LOG_LEVEL=info
      - INPUT_FILE=./input.txt

  frontend:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_BASE_URL=http://backend:3003
    depends_on:
      - backend